### ISSUE TITLE
Patmat doesn't succeed to recognize type list

### ISSUE THREAD

**Issue by Atch0um** [admk/patmat#2]
Hi,
Your tool is amazing, but I've this bug. Do you have any Idea ?

When I do this : 
```
@case
def func(_, l=Type(list)):
    print l

func([1, 2, 3])
```
I have this error : 
```
patmat.match.FunctionNotMatched: Function call `func(l=[1, 2, 3])` cannot be matched.
```

**Comment by mitghi** [comment]
Which version are you using ? 
I can't reproduce it on patmat 1.0.1.

**Comment by Atch0um** [comment]
I have exactly this version of patmat.
My cases are in a wrapper in a class.
my code looks like that:
```
class A:
    def run(self):
        @case
        def func(_, l=Type(B)):
              pass
        @case
        def func(_, l=Type(list)):
              pass
        @case
        def func(_, l=Type(int)):
              pass
        func([1, 2, 3]) # Fail
        func(1) # Fail
        func(B("foo")) # succeed
```
All my primitive types fails.
Do you have any Idea  ?

**Comment by mitghi** [comment]
Last example worked on version 1.0.1 . However, when B instance works it indicates that a type class of desired primitive type should theoricaly also work.

Try extending list in a class and see what happens.
I will check it later when i have access to my computer.

**Comment by Atch0um** [comment]
I think i found why I was buggy:
one of my case was named differently:
```
@case
def func(_, x=...):
    ...
@case
def func(_, l=...):
    ...
@case
def func(_, x=...):
    ...
@case
def func(_, x=...):
    ...
```
