### ISSUE TITLE
Loop in case bug

### ISSUE THREAD

**Issue by Atch0um** [admk/patmat#3]
Hi,
I have one another bug.
```
        @case
        def func(_, l=Type(list)):
            print("this is a list")
            for e in l:
                print(e)
...
SyntaxError: Each argument must have a default value.
```
I don't understand why this exception raised.

**Comment by mitghi** [comment]
You should use match probably and iter through match element. Check the examples.

Milad Taghavi

**Comment by Atch0um** [comment]
I added a new wrapper and iterate in it. Thx a lot !
